version: "3"

services:
    db:
        container_name: pg_db
        restart: always
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: kekw
        volumes: 
            - ./postgres_data:/var/lib/postgresql/data
        ports: 
            - 5432:5432
    pgadmin: 
        container_name: pgadmin
        restart: always
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
            PGADMIN_DEFAULT_PASSWORD: 1234
        ports:
            - 5050:80
    main:
        container_name: main
        restart: always
        build: .
        ports: 
            - 8000:8000
        depends_on:
            - pg_db
        